### PR TITLE
Added flask backend for movie recommendation 

### PR DESCRIPTION
**Pull request by deathsurgeon1**
Added flask backend for movie recommendation for issue #1

### CODE REVIEW

**Comment by deathsurgeon1** [comment]
Hi @Aryan-2003 I have added changes for supporting flask web app and frontend based on react framework. Please review.
The movie recommendation frontend is live on : https://moviesuggestionfrontend2022.herokuapp.com/. You can visit this link and see the UI experience.

As of now it is simple but can be improved.

**Comment by Aryan-2003** [comment]
@deathsurgeon1 the deployed web-app is giving application error

please check it and request the PR again

**Comment by deathsurgeon1** [comment]
Hi @Aryan-2003 , please check the deployment here: https://frontendtest1-4excfe4na-deathsurgeon1.vercel.app/

**Comment by Aryan-2003** [comment]
@deathsurgeon1 confirm whether the merge request is visible in your hacktoberfest account

**Comment by deathsurgeon1** [comment]
Hi @Aryan-2003 , yeah I can see the request in hacktoberfest account.

**Comment by Aryan-2003** [comment]
Ok

**Pull request merged**
